"""Add community features: forums, marketplace, gamification, notifications

Revision ID: 66d67212a85f
Revises: f1f3118c407c
Create Date: 2025-08-02 01:03:31.322655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66d67212a85f'
down_revision: Union[str, None] = 'f1f3118c407c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('badge_color', sa.String(length=7), nullable=True),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('points_required', sa.Integer(), nullable=True),
    sa.Column('level_required', sa.Integer(), nullable=True),
    sa.Column('points_reward', sa.Integer(), nullable=True),
    sa.Column('badge_title', sa.String(length=100), nullable=True),
    sa.Column('rarity', sa.String(length=20), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=True),
    sa.Column('is_repeatable', sa.Boolean(), nullable=True),
    sa.Column('total_earned', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_achievements_category'), 'achievements', ['category'], unique=False)
    op.create_index(op.f('ix_achievements_id'), 'achievements', ['id'], unique=False)
    op.create_index(op.f('ix_achievements_name'), 'achievements', ['name'], unique=True)
    op.create_index(op.f('ix_achievements_type'), 'achievements', ['type'], unique=False)
    op.create_table('feature_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feature_name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('requires_moderation', sa.Boolean(), nullable=False),
    sa.Column('default_enabled', sa.Boolean(), nullable=False),
    sa.Column('configuration_schema', sa.Text(), nullable=True),
    sa.Column('compliance_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_configurations_created_at'), 'feature_configurations', ['created_at'], unique=False)
    op.create_index(op.f('ix_feature_configurations_feature_name'), 'feature_configurations', ['feature_name'], unique=True)
    op.create_index(op.f('ix_feature_configurations_id'), 'feature_configurations', ['id'], unique=False)
    op.create_table('feature_toggles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('feature_name', sa.String(length=100), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('configuration', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('requires_moderation', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_toggles_created_at'), 'feature_toggles', ['created_at'], unique=False)
    op.create_index(op.f('ix_feature_toggles_feature_name'), 'feature_toggles', ['feature_name'], unique=False)
    op.create_index(op.f('ix_feature_toggles_id'), 'feature_toggles', ['id'], unique=False)
    op.create_index(op.f('ix_feature_toggles_organization_id'), 'feature_toggles', ['organization_id'], unique=False)
    op.create_table('activity_feeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('activity_description', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('visibility_level', sa.String(length=20), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('activity_metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_feeds_activity_type'), 'activity_feeds', ['activity_type'], unique=False)
    op.create_index(op.f('ix_activity_feeds_created_at'), 'activity_feeds', ['created_at'], unique=False)
    op.create_index(op.f('ix_activity_feeds_id'), 'activity_feeds', ['id'], unique=False)
    op.create_index(op.f('ix_activity_feeds_user_id'), 'activity_feeds', ['user_id'], unique=False)
    op.create_table('forum_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('is_global', sa.Boolean(), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=True),
    sa.Column('moderator_only', sa.Boolean(), nullable=True),
    sa.Column('topic_count', sa.Integer(), nullable=True),
    sa.Column('post_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['users.organization_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forum_categories_id'), 'forum_categories', ['id'], unique=False)
    op.create_index(op.f('ix_forum_categories_organization_id'), 'forum_categories', ['organization_id'], unique=False)
    op.create_index(op.f('ix_forum_categories_slug'), 'forum_categories', ['slug'], unique=True)
    op.create_table('leaderboards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('time_period', sa.String(length=20), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('previous_rank', sa.Integer(), nullable=True),
    sa.Column('rank_change', sa.Integer(), nullable=True),
    sa.Column('metric_value', sa.Integer(), nullable=True),
    sa.Column('metric_description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leaderboards_category'), 'leaderboards', ['category'], unique=False)
    op.create_index(op.f('ix_leaderboards_id'), 'leaderboards', ['id'], unique=False)
    op.create_index(op.f('ix_leaderboards_period_end'), 'leaderboards', ['period_end'], unique=False)
    op.create_index(op.f('ix_leaderboards_period_start'), 'leaderboards', ['period_start'], unique=False)
    op.create_index(op.f('ix_leaderboards_rank'), 'leaderboards', ['rank'], unique=False)
    op.create_index(op.f('ix_leaderboards_time_period'), 'leaderboards', ['time_period'], unique=False)
    op.create_index(op.f('ix_leaderboards_user_id'), 'leaderboards', ['user_id'], unique=False)
    op.create_table('networking_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('start_datetime', sa.DateTime(), nullable=False),
    sa.Column('end_datetime', sa.DateTime(), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('is_virtual', sa.Boolean(), nullable=True),
    sa.Column('venue_name', sa.String(length=255), nullable=True),
    sa.Column('venue_address', sa.Text(), nullable=True),
    sa.Column('meeting_url', sa.String(length=500), nullable=True),
    sa.Column('meeting_password', sa.String(length=100), nullable=True),
    sa.Column('organizer_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('max_attendees', sa.Integer(), nullable=True),
    sa.Column('registration_required', sa.Boolean(), nullable=True),
    sa.Column('registration_deadline', sa.DateTime(), nullable=True),
    sa.Column('is_free', sa.Boolean(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('agenda', sa.Text(), nullable=True),
    sa.Column('speakers', sa.Text(), nullable=True),
    sa.Column('materials', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('registration_count', sa.Integer(), nullable=True),
    sa.Column('attendance_count', sa.Integer(), nullable=True),
    sa.Column('recording_url', sa.String(length=500), nullable=True),
    sa.Column('recording_available', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['users.organization_id'], ),
    sa.ForeignKeyConstraint(['organizer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_networking_events_id'), 'networking_events', ['id'], unique=False)
    op.create_index(op.f('ix_networking_events_organization_id'), 'networking_events', ['organization_id'], unique=False)
    op.create_index(op.f('ix_networking_events_organizer_id'), 'networking_events', ['organizer_id'], unique=False)
    op.create_index(op.f('ix_networking_events_start_datetime'), 'networking_events', ['start_datetime'], unique=False)
    op.create_index(op.f('ix_networking_events_title'), 'networking_events', ['title'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email_notifications', sa.Boolean(), nullable=True),
    sa.Column('push_notifications', sa.Boolean(), nullable=True),
    sa.Column('sms_notifications', sa.Boolean(), nullable=True),
    sa.Column('grant_updates', sa.Boolean(), nullable=True),
    sa.Column('application_status', sa.Boolean(), nullable=True),
    sa.Column('community_activity', sa.Boolean(), nullable=True),
    sa.Column('professional_services', sa.Boolean(), nullable=True),
    sa.Column('achievements', sa.Boolean(), nullable=True),
    sa.Column('system_updates', sa.Boolean(), nullable=True),
    sa.Column('marketing', sa.Boolean(), nullable=True),
    sa.Column('digest_frequency', sa.String(length=20), nullable=True),
    sa.Column('quiet_hours_start', sa.String(length=5), nullable=True),
    sa.Column('quiet_hours_end', sa.String(length=5), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('notification_sound', sa.Boolean(), nullable=True),
    sa.Column('desktop_notifications', sa.Boolean(), nullable=True),
    sa.Column('mobile_notifications', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_preferences_id'), 'notification_preferences', ['id'], unique=False)
    op.create_index(op.f('ix_notification_preferences_user_id'), 'notification_preferences', ['user_id'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('delivery_method', sa.String(length=20), nullable=True),
    sa.Column('email_sent', sa.Boolean(), nullable=True),
    sa.Column('email_sent_at', sa.DateTime(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('group_key', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_category'), 'notifications', ['category'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('point_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_points', sa.Integer(), nullable=True),
    sa.Column('multiplier', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('bonus_points', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_point_transactions_category'), 'point_transactions', ['category'], unique=False)
    op.create_index(op.f('ix_point_transactions_created_at'), 'point_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_point_transactions_id'), 'point_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_point_transactions_transaction_type'), 'point_transactions', ['transaction_type'], unique=False)
    op.create_index(op.f('ix_point_transactions_user_id'), 'point_transactions', ['user_id'], unique=False)
    op.create_table('professional_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=True),
    sa.Column('business_registration', sa.String(length=100), nullable=True),
    sa.Column('abn_acn', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('specializations', sa.Text(), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('linkedin_url', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('postcode', sa.String(length=10), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('service_areas', sa.Text(), nullable=True),
    sa.Column('remote_services', sa.Boolean(), nullable=True),
    sa.Column('qualifications', sa.Text(), nullable=True),
    sa.Column('portfolio_items', sa.Text(), nullable=True),
    sa.Column('application_status', sa.Enum('PENDING', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'SUSPENDED', name='applicationstatus'), nullable=True),
    sa.Column('application_date', sa.DateTime(), nullable=True),
    sa.Column('approval_date', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('total_bookings', sa.Integer(), nullable=True),
    sa.Column('completed_projects', sa.Integer(), nullable=True),
    sa.Column('average_rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('total_reviews', sa.Integer(), nullable=True),
    sa.Column('response_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('response_time_hours', sa.Integer(), nullable=True),
    sa.Column('hourly_rate_min', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('hourly_rate_max', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('project_rate_min', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('project_rate_max', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_professional_profiles_application_status'), 'professional_profiles', ['application_status'], unique=False)
    op.create_index(op.f('ix_professional_profiles_id'), 'professional_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_professional_profiles_user_id'), 'professional_profiles', ['user_id'], unique=True)
    op.create_table('resource_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('is_global', sa.Boolean(), nullable=True),
    sa.Column('resource_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['users.organization_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_categories_id'), 'resource_categories', ['id'], unique=False)
    op.create_index(op.f('ix_resource_categories_organization_id'), 'resource_categories', ['organization_id'], unique=False)
    op.create_index(op.f('ix_resource_categories_slug'), 'resource_categories', ['slug'], unique=True)
    op.create_table('user_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('is_mutual', sa.Boolean(), nullable=True),
    sa.Column('last_interaction', sa.DateTime(), nullable=True),
    sa.Column('interaction_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_connections_id'), 'user_connections', ['id'], unique=False)
    op.create_index(op.f('ix_user_connections_recipient_id'), 'user_connections', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_user_connections_requester_id'), 'user_connections', ['requester_id'], unique=False)
    op.create_index(op.f('ix_user_connections_status'), 'user_connections', ['status'], unique=False)
    op.create_table('user_follows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('following_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['following_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_follows_follower_id'), 'user_follows', ['follower_id'], unique=False)
    op.create_index(op.f('ix_user_follows_following_id'), 'user_follows', ['following_id'], unique=False)
    op.create_index(op.f('ix_user_follows_id'), 'user_follows', ['id'], unique=False)
    op.create_table('user_interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('grant_categories', sa.Text(), nullable=True),
    sa.Column('project_types', sa.Text(), nullable=True),
    sa.Column('funding_amounts', sa.Text(), nullable=True),
    sa.Column('geographic_areas', sa.Text(), nullable=True),
    sa.Column('service_categories', sa.Text(), nullable=True),
    sa.Column('collaboration_interests', sa.Text(), nullable=True),
    sa.Column('learning_topics', sa.Text(), nullable=True),
    sa.Column('event_preferences', sa.Text(), nullable=True),
    sa.Column('newsletter_frequency', sa.String(length=20), nullable=True),
    sa.Column('notification_preferences', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_interests_id'), 'user_interests', ['id'], unique=False)
    op.create_index(op.f('ix_user_interests_user_id'), 'user_interests', ['user_id'], unique=False)
    op.create_table('user_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=True),
    sa.Column('current_level', sa.Integer(), nullable=True),
    sa.Column('points_to_next_level', sa.Integer(), nullable=True),
    sa.Column('grant_points', sa.Integer(), nullable=True),
    sa.Column('community_points', sa.Integer(), nullable=True),
    sa.Column('knowledge_points', sa.Integer(), nullable=True),
    sa.Column('networking_points', sa.Integer(), nullable=True),
    sa.Column('professional_points', sa.Integer(), nullable=True),
    sa.Column('daily_login_streak', sa.Integer(), nullable=True),
    sa.Column('max_login_streak', sa.Integer(), nullable=True),
    sa.Column('last_login_date', sa.DateTime(), nullable=True),
    sa.Column('grants_applied', sa.Integer(), nullable=True),
    sa.Column('grants_won', sa.Integer(), nullable=True),
    sa.Column('forum_posts', sa.Integer(), nullable=True),
    sa.Column('resources_shared', sa.Integer(), nullable=True),
    sa.Column('connections_made', sa.Integer(), nullable=True),
    sa.Column('events_attended', sa.Integer(), nullable=True),
    sa.Column('total_achievements', sa.Integer(), nullable=True),
    sa.Column('rare_achievements', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_levels_current_level'), 'user_levels', ['current_level'], unique=False)
    op.create_index(op.f('ix_user_levels_id'), 'user_levels', ['id'], unique=False)
    op.create_index(op.f('ix_user_levels_total_points'), 'user_levels', ['total_points'], unique=False)
    op.create_index(op.f('ix_user_levels_user_id'), 'user_levels', ['user_id'], unique=True)
    op.create_table('activity_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('parent_comment_id', sa.Integer(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity_feeds.id'], ),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['activity_comments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_comments_activity_id'), 'activity_comments', ['activity_id'], unique=False)
    op.create_index(op.f('ix_activity_comments_id'), 'activity_comments', ['id'], unique=False)
    op.create_index(op.f('ix_activity_comments_user_id'), 'activity_comments', ['user_id'], unique=False)
    op.create_table('activity_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity_feeds.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_likes_activity_id'), 'activity_likes', ['activity_id'], unique=False)
    op.create_index(op.f('ix_activity_likes_id'), 'activity_likes', ['id'], unique=False)
    op.create_index(op.f('ix_activity_likes_user_id'), 'activity_likes', ['user_id'], unique=False)
    op.create_table('event_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('questions_responses', sa.Text(), nullable=True),
    sa.Column('dietary_requirements', sa.Text(), nullable=True),
    sa.Column('accessibility_needs', sa.Text(), nullable=True),
    sa.Column('attended', sa.Boolean(), nullable=True),
    sa.Column('attendance_duration', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['networking_events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_registrations_event_id'), 'event_registrations', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_registrations_id'), 'event_registrations', ['id'], unique=False)
    op.create_index(op.f('ix_event_registrations_user_id'), 'event_registrations', ['user_id'], unique=False)
    op.create_table('forum_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('reply_count', sa.Integer(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('last_post_at', sa.DateTime(), nullable=True),
    sa.Column('last_post_by', sa.Integer(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['forum_categories.id'], ),
    sa.ForeignKeyConstraint(['last_post_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['users.organization_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forum_topics_author_id'), 'forum_topics', ['author_id'], unique=False)
    op.create_index(op.f('ix_forum_topics_category_id'), 'forum_topics', ['category_id'], unique=False)
    op.create_index(op.f('ix_forum_topics_id'), 'forum_topics', ['id'], unique=False)
    op.create_index(op.f('ix_forum_topics_organization_id'), 'forum_topics', ['organization_id'], unique=False)
    op.create_index(op.f('ix_forum_topics_slug'), 'forum_topics', ['slug'], unique=False)
    op.create_index(op.f('ix_forum_topics_title'), 'forum_topics', ['title'], unique=False)
    op.create_table('professional_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('professional_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['professional_id'], ['professional_profiles.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_professional_documents_id'), 'professional_documents', ['id'], unique=False)
    op.create_index(op.f('ix_professional_documents_professional_id'), 'professional_documents', ['professional_id'], unique=False)
    op.create_table('professional_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('professional_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('GRANT_WRITING', 'FINANCIAL_ADVISORY', 'STRATEGIC_CONSULTING', 'LEGAL_ADVISORY', 'PROJECT_MANAGEMENT', 'EVALUATION_REPORTING', 'TRAINING_WORKSHOPS', 'MARKETING_COMMUNICATIONS', 'TECHNICAL_SUPPORT', 'OTHER', name='servicecategory'), nullable=False),
    sa.Column('pricing_type', sa.String(length=20), nullable=False),
    sa.Column('hourly_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fixed_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_description', sa.Text(), nullable=True),
    sa.Column('duration_estimate', sa.String(length=100), nullable=True),
    sa.Column('deliverables', sa.Text(), nullable=True),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('max_concurrent_projects', sa.Integer(), nullable=True),
    sa.Column('booking_count', sa.Integer(), nullable=True),
    sa.Column('completion_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('average_rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['professional_id'], ['professional_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_professional_services_category'), 'professional_services', ['category'], unique=False)
    op.create_index(op.f('ix_professional_services_id'), 'professional_services', ['id'], unique=False)
    op.create_index(op.f('ix_professional_services_professional_id'), 'professional_services', ['professional_id'], unique=False)
    op.create_index(op.f('ix_professional_services_title'), 'professional_services', ['title'], unique=False)
    op.create_table('resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('resource_type', sa.String(length=20), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('external_url', sa.String(length=500), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('rating_average', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('rating_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['resource_categories.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['users.organization_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resources_author_id'), 'resources', ['author_id'], unique=False)
    op.create_index(op.f('ix_resources_category_id'), 'resources', ['category_id'], unique=False)
    op.create_index(op.f('ix_resources_id'), 'resources', ['id'], unique=False)
    op.create_index(op.f('ix_resources_organization_id'), 'resources', ['organization_id'], unique=False)
    op.create_index(op.f('ix_resources_resource_type'), 'resources', ['resource_type'], unique=False)
    op.create_index(op.f('ix_resources_slug'), 'resources', ['slug'], unique=False)
    op.create_index(op.f('ix_resources_title'), 'resources', ['title'], unique=False)
    op.create_table('success_stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('grant_id', sa.Integer(), nullable=True),
    sa.Column('grant_title', sa.String(length=255), nullable=True),
    sa.Column('grant_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('funding_organization', sa.String(length=255), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('organization_name', sa.String(length=255), nullable=False),
    sa.Column('organization_type', sa.String(length=100), nullable=True),
    sa.Column('organization_size', sa.String(length=50), nullable=True),
    sa.Column('project_category', sa.String(length=100), nullable=True),
    sa.Column('project_duration', sa.String(length=100), nullable=True),
    sa.Column('beneficiaries_count', sa.Integer(), nullable=True),
    sa.Column('beneficiaries_description', sa.Text(), nullable=True),
    sa.Column('impact_metrics', sa.Text(), nullable=True),
    sa.Column('outcomes_achieved', sa.Text(), nullable=True),
    sa.Column('lessons_learned', sa.Text(), nullable=True),
    sa.Column('featured_image_url', sa.String(length=500), nullable=True),
    sa.Column('gallery_images', sa.Text(), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('author_name', sa.String(length=255), nullable=True),
    sa.Column('author_title', sa.String(length=255), nullable=True),
    sa.Column('used_professional_services', sa.Boolean(), nullable=True),
    sa.Column('professional_services_used', sa.Text(), nullable=True),
    sa.Column('professional_testimonial', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('share_count', sa.Integer(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['grant_id'], ['grants.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['users.organization_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_success_stories_author_id'), 'success_stories', ['author_id'], unique=False)
    op.create_index(op.f('ix_success_stories_grant_id'), 'success_stories', ['grant_id'], unique=False)
    op.create_index(op.f('ix_success_stories_id'), 'success_stories', ['id'], unique=False)
    op.create_index(op.f('ix_success_stories_is_featured'), 'success_stories', ['is_featured'], unique=False)
    op.create_index(op.f('ix_success_stories_organization_id'), 'success_stories', ['organization_id'], unique=False)
    op.create_index(op.f('ix_success_stories_slug'), 'success_stories', ['slug'], unique=True)
    op.create_index(op.f('ix_success_stories_status'), 'success_stories', ['status'], unique=False)
    op.create_index(op.f('ix_success_stories_title'), 'success_stories', ['title'], unique=False)
    op.create_table('user_achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('user_level_id', sa.Integer(), nullable=False),
    sa.Column('earned_at', sa.DateTime(), nullable=True),
    sa.Column('points_earned', sa.Integer(), nullable=True),
    sa.Column('progress_count', sa.Integer(), nullable=True),
    sa.Column('is_displayed', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_level_id'], ['user_levels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_achievements_achievement_id'), 'user_achievements', ['achievement_id'], unique=False)
    op.create_index(op.f('ix_user_achievements_earned_at'), 'user_achievements', ['earned_at'], unique=False)
    op.create_index(op.f('ix_user_achievements_id'), 'user_achievements', ['id'], unique=False)
    op.create_index(op.f('ix_user_achievements_user_id'), 'user_achievements', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_achievements_user_level_id'), 'user_achievements', ['user_level_id'], unique=False)
    op.create_table('forum_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('parent_post_id', sa.Integer(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('is_solution', sa.Boolean(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.Column('edited_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['edited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_post_id'], ['forum_posts.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['forum_topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forum_posts_author_id'), 'forum_posts', ['author_id'], unique=False)
    op.create_index(op.f('ix_forum_posts_id'), 'forum_posts', ['id'], unique=False)
    op.create_index(op.f('ix_forum_posts_parent_post_id'), 'forum_posts', ['parent_post_id'], unique=False)
    op.create_index(op.f('ix_forum_posts_topic_id'), 'forum_posts', ['topic_id'], unique=False)
    op.create_table('forum_topic_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['forum_topics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forum_topic_likes_id'), 'forum_topic_likes', ['id'], unique=False)
    op.create_index(op.f('ix_forum_topic_likes_topic_id'), 'forum_topic_likes', ['topic_id'], unique=False)
    op.create_index(op.f('ix_forum_topic_likes_user_id'), 'forum_topic_likes', ['user_id'], unique=False)
    op.create_table('resource_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_likes_id'), 'resource_likes', ['id'], unique=False)
    op.create_index(op.f('ix_resource_likes_resource_id'), 'resource_likes', ['resource_id'], unique=False)
    op.create_index(op.f('ix_resource_likes_user_id'), 'resource_likes', ['user_id'], unique=False)
    op.create_table('resource_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_ratings_id'), 'resource_ratings', ['id'], unique=False)
    op.create_index(op.f('ix_resource_ratings_resource_id'), 'resource_ratings', ['resource_id'], unique=False)
    op.create_index(op.f('ix_resource_ratings_user_id'), 'resource_ratings', ['user_id'], unique=False)
    op.create_table('service_bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_reference', sa.String(length=20), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('professional_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('preferred_start_date', sa.DateTime(), nullable=True),
    sa.Column('actual_start_date', sa.DateTime(), nullable=True),
    sa.Column('estimated_completion', sa.DateTime(), nullable=True),
    sa.Column('actual_completion', sa.DateTime(), nullable=True),
    sa.Column('quoted_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('final_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pricing_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'DISPUTED', name='bookingstatus'), nullable=True),
    sa.Column('client_notes', sa.Text(), nullable=True),
    sa.Column('professional_notes', sa.Text(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('milestones', sa.Text(), nullable=True),
    sa.Column('progress_updates', sa.Text(), nullable=True),
    sa.Column('client_files', sa.Text(), nullable=True),
    sa.Column('deliverable_files', sa.Text(), nullable=True),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('unread_messages_client', sa.Integer(), nullable=True),
    sa.Column('unread_messages_professional', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['professional_id'], ['professional_profiles.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['professional_services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_bookings_booking_reference'), 'service_bookings', ['booking_reference'], unique=True)
    op.create_index(op.f('ix_service_bookings_client_id'), 'service_bookings', ['client_id'], unique=False)
    op.create_index(op.f('ix_service_bookings_id'), 'service_bookings', ['id'], unique=False)
    op.create_index(op.f('ix_service_bookings_professional_id'), 'service_bookings', ['professional_id'], unique=False)
    op.create_index(op.f('ix_service_bookings_service_id'), 'service_bookings', ['service_id'], unique=False)
    op.create_index(op.f('ix_service_bookings_status'), 'service_bookings', ['status'], unique=False)
    op.create_table('story_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('parent_comment_id', sa.Integer(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['story_comments.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['success_stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_comments_author_id'), 'story_comments', ['author_id'], unique=False)
    op.create_index(op.f('ix_story_comments_id'), 'story_comments', ['id'], unique=False)
    op.create_index(op.f('ix_story_comments_parent_comment_id'), 'story_comments', ['parent_comment_id'], unique=False)
    op.create_index(op.f('ix_story_comments_story_id'), 'story_comments', ['story_id'], unique=False)
    op.create_table('story_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['success_stories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_likes_id'), 'story_likes', ['id'], unique=False)
    op.create_index(op.f('ix_story_likes_story_id'), 'story_likes', ['story_id'], unique=False)
    op.create_index(op.f('ix_story_likes_user_id'), 'story_likes', ['user_id'], unique=False)
    op.create_table('booking_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('message_type', sa.String(length=20), nullable=True),
    sa.Column('attachments', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('is_system_message', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['service_bookings.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_messages_booking_id'), 'booking_messages', ['booking_id'], unique=False)
    op.create_index(op.f('ix_booking_messages_id'), 'booking_messages', ['id'], unique=False)
    op.create_index(op.f('ix_booking_messages_sender_id'), 'booking_messages', ['sender_id'], unique=False)
    op.create_table('comment_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['story_comments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_likes_comment_id'), 'comment_likes', ['comment_id'], unique=False)
    op.create_index(op.f('ix_comment_likes_id'), 'comment_likes', ['id'], unique=False)
    op.create_index(op.f('ix_comment_likes_user_id'), 'comment_likes', ['user_id'], unique=False)
    op.create_table('forum_post_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['forum_posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forum_post_likes_id'), 'forum_post_likes', ['id'], unique=False)
    op.create_index(op.f('ix_forum_post_likes_post_id'), 'forum_post_likes', ['post_id'], unique=False)
    op.create_index(op.f('ix_forum_post_likes_user_id'), 'forum_post_likes', ['user_id'], unique=False)
    op.create_table('professional_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('professional_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('overall_rating', sa.Integer(), nullable=False),
    sa.Column('communication_rating', sa.Integer(), nullable=True),
    sa.Column('quality_rating', sa.Integer(), nullable=True),
    sa.Column('timeliness_rating', sa.Integer(), nullable=True),
    sa.Column('value_rating', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('would_recommend', sa.Boolean(), nullable=True),
    sa.Column('professional_response', sa.Text(), nullable=True),
    sa.Column('response_date', sa.DateTime(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['service_bookings.id'], ),
    sa.ForeignKeyConstraint(['professional_id'], ['professional_profiles.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_professional_reviews_booking_id'), 'professional_reviews', ['booking_id'], unique=False)
    op.create_index(op.f('ix_professional_reviews_id'), 'professional_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_professional_reviews_professional_id'), 'professional_reviews', ['professional_id'], unique=False)
    op.create_index(op.f('ix_professional_reviews_reviewer_id'), 'professional_reviews', ['reviewer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_professional_reviews_reviewer_id'), table_name='professional_reviews')
    op.drop_index(op.f('ix_professional_reviews_professional_id'), table_name='professional_reviews')
    op.drop_index(op.f('ix_professional_reviews_id'), table_name='professional_reviews')
    op.drop_index(op.f('ix_professional_reviews_booking_id'), table_name='professional_reviews')
    op.drop_table('professional_reviews')
    op.drop_index(op.f('ix_forum_post_likes_user_id'), table_name='forum_post_likes')
    op.drop_index(op.f('ix_forum_post_likes_post_id'), table_name='forum_post_likes')
    op.drop_index(op.f('ix_forum_post_likes_id'), table_name='forum_post_likes')
    op.drop_table('forum_post_likes')
    op.drop_index(op.f('ix_comment_likes_user_id'), table_name='comment_likes')
    op.drop_index(op.f('ix_comment_likes_id'), table_name='comment_likes')
    op.drop_index(op.f('ix_comment_likes_comment_id'), table_name='comment_likes')
    op.drop_table('comment_likes')
    op.drop_index(op.f('ix_booking_messages_sender_id'), table_name='booking_messages')
    op.drop_index(op.f('ix_booking_messages_id'), table_name='booking_messages')
    op.drop_index(op.f('ix_booking_messages_booking_id'), table_name='booking_messages')
    op.drop_table('booking_messages')
    op.drop_index(op.f('ix_story_likes_user_id'), table_name='story_likes')
    op.drop_index(op.f('ix_story_likes_story_id'), table_name='story_likes')
    op.drop_index(op.f('ix_story_likes_id'), table_name='story_likes')
    op.drop_table('story_likes')
    op.drop_index(op.f('ix_story_comments_story_id'), table_name='story_comments')
    op.drop_index(op.f('ix_story_comments_parent_comment_id'), table_name='story_comments')
    op.drop_index(op.f('ix_story_comments_id'), table_name='story_comments')
    op.drop_index(op.f('ix_story_comments_author_id'), table_name='story_comments')
    op.drop_table('story_comments')
    op.drop_index(op.f('ix_service_bookings_status'), table_name='service_bookings')
    op.drop_index(op.f('ix_service_bookings_service_id'), table_name='service_bookings')
    op.drop_index(op.f('ix_service_bookings_professional_id'), table_name='service_bookings')
    op.drop_index(op.f('ix_service_bookings_id'), table_name='service_bookings')
    op.drop_index(op.f('ix_service_bookings_client_id'), table_name='service_bookings')
    op.drop_index(op.f('ix_service_bookings_booking_reference'), table_name='service_bookings')
    op.drop_table('service_bookings')
    op.drop_index(op.f('ix_resource_ratings_user_id'), table_name='resource_ratings')
    op.drop_index(op.f('ix_resource_ratings_resource_id'), table_name='resource_ratings')
    op.drop_index(op.f('ix_resource_ratings_id'), table_name='resource_ratings')
    op.drop_table('resource_ratings')
    op.drop_index(op.f('ix_resource_likes_user_id'), table_name='resource_likes')
    op.drop_index(op.f('ix_resource_likes_resource_id'), table_name='resource_likes')
    op.drop_index(op.f('ix_resource_likes_id'), table_name='resource_likes')
    op.drop_table('resource_likes')
    op.drop_index(op.f('ix_forum_topic_likes_user_id'), table_name='forum_topic_likes')
    op.drop_index(op.f('ix_forum_topic_likes_topic_id'), table_name='forum_topic_likes')
    op.drop_index(op.f('ix_forum_topic_likes_id'), table_name='forum_topic_likes')
    op.drop_table('forum_topic_likes')
    op.drop_index(op.f('ix_forum_posts_topic_id'), table_name='forum_posts')
    op.drop_index(op.f('ix_forum_posts_parent_post_id'), table_name='forum_posts')
    op.drop_index(op.f('ix_forum_posts_id'), table_name='forum_posts')
    op.drop_index(op.f('ix_forum_posts_author_id'), table_name='forum_posts')
    op.drop_table('forum_posts')
    op.drop_index(op.f('ix_user_achievements_user_level_id'), table_name='user_achievements')
    op.drop_index(op.f('ix_user_achievements_user_id'), table_name='user_achievements')
    op.drop_index(op.f('ix_user_achievements_id'), table_name='user_achievements')
    op.drop_index(op.f('ix_user_achievements_earned_at'), table_name='user_achievements')
    op.drop_index(op.f('ix_user_achievements_achievement_id'), table_name='user_achievements')
    op.drop_table('user_achievements')
    op.drop_index(op.f('ix_success_stories_title'), table_name='success_stories')
    op.drop_index(op.f('ix_success_stories_status'), table_name='success_stories')
    op.drop_index(op.f('ix_success_stories_slug'), table_name='success_stories')
    op.drop_index(op.f('ix_success_stories_organization_id'), table_name='success_stories')
    op.drop_index(op.f('ix_success_stories_is_featured'), table_name='success_stories')
    op.drop_index(op.f('ix_success_stories_id'), table_name='success_stories')
    op.drop_index(op.f('ix_success_stories_grant_id'), table_name='success_stories')
    op.drop_index(op.f('ix_success_stories_author_id'), table_name='success_stories')
    op.drop_table('success_stories')
    op.drop_index(op.f('ix_resources_title'), table_name='resources')
    op.drop_index(op.f('ix_resources_slug'), table_name='resources')
    op.drop_index(op.f('ix_resources_resource_type'), table_name='resources')
    op.drop_index(op.f('ix_resources_organization_id'), table_name='resources')
    op.drop_index(op.f('ix_resources_id'), table_name='resources')
    op.drop_index(op.f('ix_resources_category_id'), table_name='resources')
    op.drop_index(op.f('ix_resources_author_id'), table_name='resources')
    op.drop_table('resources')
    op.drop_index(op.f('ix_professional_services_title'), table_name='professional_services')
    op.drop_index(op.f('ix_professional_services_professional_id'), table_name='professional_services')
    op.drop_index(op.f('ix_professional_services_id'), table_name='professional_services')
    op.drop_index(op.f('ix_professional_services_category'), table_name='professional_services')
    op.drop_table('professional_services')
    op.drop_index(op.f('ix_professional_documents_professional_id'), table_name='professional_documents')
    op.drop_index(op.f('ix_professional_documents_id'), table_name='professional_documents')
    op.drop_table('professional_documents')
    op.drop_index(op.f('ix_forum_topics_title'), table_name='forum_topics')
    op.drop_index(op.f('ix_forum_topics_slug'), table_name='forum_topics')
    op.drop_index(op.f('ix_forum_topics_organization_id'), table_name='forum_topics')
    op.drop_index(op.f('ix_forum_topics_id'), table_name='forum_topics')
    op.drop_index(op.f('ix_forum_topics_category_id'), table_name='forum_topics')
    op.drop_index(op.f('ix_forum_topics_author_id'), table_name='forum_topics')
    op.drop_table('forum_topics')
    op.drop_index(op.f('ix_event_registrations_user_id'), table_name='event_registrations')
    op.drop_index(op.f('ix_event_registrations_id'), table_name='event_registrations')
    op.drop_index(op.f('ix_event_registrations_event_id'), table_name='event_registrations')
    op.drop_table('event_registrations')
    op.drop_index(op.f('ix_activity_likes_user_id'), table_name='activity_likes')
    op.drop_index(op.f('ix_activity_likes_id'), table_name='activity_likes')
    op.drop_index(op.f('ix_activity_likes_activity_id'), table_name='activity_likes')
    op.drop_table('activity_likes')
    op.drop_index(op.f('ix_activity_comments_user_id'), table_name='activity_comments')
    op.drop_index(op.f('ix_activity_comments_id'), table_name='activity_comments')
    op.drop_index(op.f('ix_activity_comments_activity_id'), table_name='activity_comments')
    op.drop_table('activity_comments')
    op.drop_index(op.f('ix_user_levels_user_id'), table_name='user_levels')
    op.drop_index(op.f('ix_user_levels_total_points'), table_name='user_levels')
    op.drop_index(op.f('ix_user_levels_id'), table_name='user_levels')
    op.drop_index(op.f('ix_user_levels_current_level'), table_name='user_levels')
    op.drop_table('user_levels')
    op.drop_index(op.f('ix_user_interests_user_id'), table_name='user_interests')
    op.drop_index(op.f('ix_user_interests_id'), table_name='user_interests')
    op.drop_table('user_interests')
    op.drop_index(op.f('ix_user_follows_id'), table_name='user_follows')
    op.drop_index(op.f('ix_user_follows_following_id'), table_name='user_follows')
    op.drop_index(op.f('ix_user_follows_follower_id'), table_name='user_follows')
    op.drop_table('user_follows')
    op.drop_index(op.f('ix_user_connections_status'), table_name='user_connections')
    op.drop_index(op.f('ix_user_connections_requester_id'), table_name='user_connections')
    op.drop_index(op.f('ix_user_connections_recipient_id'), table_name='user_connections')
    op.drop_index(op.f('ix_user_connections_id'), table_name='user_connections')
    op.drop_table('user_connections')
    op.drop_index(op.f('ix_resource_categories_slug'), table_name='resource_categories')
    op.drop_index(op.f('ix_resource_categories_organization_id'), table_name='resource_categories')
    op.drop_index(op.f('ix_resource_categories_id'), table_name='resource_categories')
    op.drop_table('resource_categories')
    op.drop_index(op.f('ix_professional_profiles_user_id'), table_name='professional_profiles')
    op.drop_index(op.f('ix_professional_profiles_id'), table_name='professional_profiles')
    op.drop_index(op.f('ix_professional_profiles_application_status'), table_name='professional_profiles')
    op.drop_table('professional_profiles')
    op.drop_index(op.f('ix_point_transactions_user_id'), table_name='point_transactions')
    op.drop_index(op.f('ix_point_transactions_transaction_type'), table_name='point_transactions')
    op.drop_index(op.f('ix_point_transactions_id'), table_name='point_transactions')
    op.drop_index(op.f('ix_point_transactions_created_at'), table_name='point_transactions')
    op.drop_index(op.f('ix_point_transactions_category'), table_name='point_transactions')
    op.drop_table('point_transactions')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_category'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_notification_preferences_user_id'), table_name='notification_preferences')
    op.drop_index(op.f('ix_notification_preferences_id'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    op.drop_index(op.f('ix_networking_events_title'), table_name='networking_events')
    op.drop_index(op.f('ix_networking_events_start_datetime'), table_name='networking_events')
    op.drop_index(op.f('ix_networking_events_organizer_id'), table_name='networking_events')
    op.drop_index(op.f('ix_networking_events_organization_id'), table_name='networking_events')
    op.drop_index(op.f('ix_networking_events_id'), table_name='networking_events')
    op.drop_table('networking_events')
    op.drop_index(op.f('ix_leaderboards_user_id'), table_name='leaderboards')
    op.drop_index(op.f('ix_leaderboards_time_period'), table_name='leaderboards')
    op.drop_index(op.f('ix_leaderboards_rank'), table_name='leaderboards')
    op.drop_index(op.f('ix_leaderboards_period_start'), table_name='leaderboards')
    op.drop_index(op.f('ix_leaderboards_period_end'), table_name='leaderboards')
    op.drop_index(op.f('ix_leaderboards_id'), table_name='leaderboards')
    op.drop_index(op.f('ix_leaderboards_category'), table_name='leaderboards')
    op.drop_table('leaderboards')
    op.drop_index(op.f('ix_forum_categories_slug'), table_name='forum_categories')
    op.drop_index(op.f('ix_forum_categories_organization_id'), table_name='forum_categories')
    op.drop_index(op.f('ix_forum_categories_id'), table_name='forum_categories')
    op.drop_table('forum_categories')
    op.drop_index(op.f('ix_activity_feeds_user_id'), table_name='activity_feeds')
    op.drop_index(op.f('ix_activity_feeds_id'), table_name='activity_feeds')
    op.drop_index(op.f('ix_activity_feeds_created_at'), table_name='activity_feeds')
    op.drop_index(op.f('ix_activity_feeds_activity_type'), table_name='activity_feeds')
    op.drop_table('activity_feeds')
    op.drop_index(op.f('ix_feature_toggles_organization_id'), table_name='feature_toggles')
    op.drop_index(op.f('ix_feature_toggles_id'), table_name='feature_toggles')
    op.drop_index(op.f('ix_feature_toggles_feature_name'), table_name='feature_toggles')
    op.drop_index(op.f('ix_feature_toggles_created_at'), table_name='feature_toggles')
    op.drop_table('feature_toggles')
    op.drop_index(op.f('ix_feature_configurations_id'), table_name='feature_configurations')
    op.drop_index(op.f('ix_feature_configurations_feature_name'), table_name='feature_configurations')
    op.drop_index(op.f('ix_feature_configurations_created_at'), table_name='feature_configurations')
    op.drop_table('feature_configurations')
    op.drop_index(op.f('ix_achievements_type'), table_name='achievements')
    op.drop_index(op.f('ix_achievements_name'), table_name='achievements')
    op.drop_index(op.f('ix_achievements_id'), table_name='achievements')
    op.drop_index(op.f('ix_achievements_category'), table_name='achievements')
    op.drop_table('achievements')
    # ### end Alembic commands ###
